export const MOCK_PRODUCTS = [
    {
        "name": "Apanados LoMASRico",
        "category": "PROMOS",
        "price": 5900,
        "description": "10 aros de cebolla + 10 camarones apanados",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Apanados LoMASRico.png",
        "variants": []
    },
    {
        "name": "Cevichada",
        "category": "PROMOS",
        "price": 29900,
        "description": "1.5 Kg de trilogías",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Cevichada.png",
        "variants": []
    },
    {
        "name": "Ceviche + Pisco Sour",
        "category": "PROMOS",
        "price": 15000,
        "description": "Elige el tamaño de tu promo",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Ceviche%20+%20Pisco%20Sour.png",
        "variants": [
            {
                "name": "500 g ceviche + 500 cc sour",
                "price": 15000,
                "isActive": true
            },
            {
                "name": "1 kg ceviche + 1 L sour",
                "price": 25000,
                "isActive": true
            }
        ]
    },
    {
        "name": "Degustación LoMASRico",
        "category": "PROMOS",
        "price": 18900,
        "description": "3 variedades de ceviche (150g c/u)",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/Degustación LoMASRico.png",
        "variants": []
    },
    {
        "name": "Dúo Gourmet",
        "category": "PROMOS",
        "price": 21900,
        "description": "2 Ceviches medianos + 2 bebidas",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "/assets/Dúo Gourmet.png",
        "variants": []
    },
    {
        "name": "MEGA PROMO",
        "category": "PROMOS",
        "price": 45900,
        "description": "Todo para compartir",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "/assets/MEGA PROMO.png",
        "variants": []
    },
    {
        "name": "MEGA PROMO!",
        "category": "PROMOS",
        "price": 25900,
        "description": "1KG Ceviche + 1/2 docena empanadas + pancitos",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/MEGA%20PROMO.png",
        "variants": []
    },
    {
        "name": "Full Bajón",
        "category": "PROMOS",
        "price": 12900,
        "description": "*Ceviche 350g + 2 empanadas + papas fritas",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/PROMO%202.png",
        "variants": []
    },
    {
        "name": "Promo Express",
        "category": "PROMOS",
        "price": 9900,
        "description": "Ceviche individual + bebida",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/Promo Express.png",
        "variants": []
    },
    {
        "name": "Ceviche LOMASRICO (250G)",
        "category": "CEVICHE LOMASRICO",
        "price": 5900,
        "description": "Elige proteínas y el tamaño que prefieras",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Ceviche%20LoMASRico.jpg",
        "variants": []
    },
    {
        "name": "Ceviche LOMASRICO (350G)",
        "category": "CEVICHE LOMASRICO",
        "price": 8900,
        "description": "Elige proteínas y el tamaño que prefieras",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Ceviche%20LoMASRico.jpg",
        "variants": []
    },
    {
        "name": "Ceviche LOMASRICO (500G)",
        "category": "CEVICHE LOMASRICO",
        "price": 11900,
        "description": "Elige proteínas y el tamaño que prefieras",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Ceviche%20LoMASRico.jpg",
        "variants": []
    },
    {
        "name": "Ceviche LOMASRICO (750G)",
        "category": "CEVICHE LOMASRICO",
        "price": 16900,
        "description": "Elige proteínas y el tamaño que prefieras",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Ceviche%20LoMASRico.jpg",
        "variants": []
    },
    {
        "name": "Ceviche LOMASRICO (1KG)",
        "category": "CEVICHE LOMASRICO",
        "price": 20900,
        "description": "Elige proteínas y el tamaño que prefieras",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Ceviche%20LoMASRico.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Sin Verduras (250g)",
        "category": "CEVICHE SIN VERDE",
        "price": 5900,
        "description": "Elige proteínas, sin verduras",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/ceviche%20(%20sin%20verduras%20)%20350%20g%20arma%20a%20tu%20gusto.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Sin Verduras (350g)",
        "category": "CEVICHE SIN VERDE",
        "price": 8900,
        "description": "Elige proteínas, sin verduras",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/ceviche%20(%20sin%20verduras%20)%20350%20g%20arma%20a%20tu%20gusto.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Sin Verduras (500g)",
        "category": "CEVICHE SIN VERDE",
        "price": 11400,
        "description": "Elige proteínas, sin verduras",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/ceviche%20(%20sin%20verduras%20)%20350%20g%20arma%20a%20tu%20gusto.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Sin Verduras (750g)",
        "category": "CEVICHE SIN VERDE",
        "price": 16900,
        "description": "Elige proteínas, sin verduras",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/ceviche%20(%20sin%20verduras%20)%20350%20g%20arma%20a%20tu%20gusto.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Sin Verduras (1KG)",
        "category": "CEVICHE SIN VERDE",
        "price": 20900,
        "description": "Elige proteínas, sin verduras",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 3,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/ceviche%20(%20sin%20verduras%20)%20350%20g%20arma%20a%20tu%20gusto.jpg",
        "variants": []
    },
    {
        "name": "2 Bowl's LoMASRico",
        "category": "BOWLS",
        "price": 11900,
        "description": "Base arroz, repollo, zanahoria y palta. Promo 2 unidades.",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/2 Bowl's LoMASRico.png",
        "variants": []
    },
    {
        "name": "Bowl Acevichado",
        "category": "BOWLS",
        "price": 6900,
        "description": "Arroz, ceviche, zanahoria, palta y salsa",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/2 Bowl's LoMASRico.png",
        "variants": []
    },
    {
        "name": "Gohan",
        "category": "GOHAN",
        "price": 6900,
        "description": "Elige tu proteína, base arroz sushi",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 1,
        "imageUrl": "/assets/Gohan.png",
        "variants": []
    },
    {
        "name": "HandRoll Camarón",
        "category": "GOHAN",
        "price": 4500,
        "description": "*Queso crema y palta + soya",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/HandRoll Salmón.jpeg",
        "variants": []
    },
    {
        "name": "HandRoll Pollo",
        "category": "GOHAN",
        "price": 4000,
        "description": "*Apanado con pollo, palta y queso crema",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Handroll de Pollo.jpg",
        "variants": []
    },
    {
        "name": "HandRoll Salmón",
        "category": "GOHAN",
        "price": 4500,
        "description": "*Queso crema y palta + soya",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/HandRoll Salmón.jpeg",
        "variants": []
    },
    {
        "name": "Acevichado LoMasRico",
        "category": "ROLLS PREMIUM",
        "price": 7900,
        "description": "Salmón fresco acevichado que envuelve un corazón cremoso de camarón, palta y queso crema. Se corona con una suave salsa verde que equilibra acidez y frescura, logrando un bocado intenso, elegante y lleno de sabor marino",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/1772879053858-3mdpt.png",
        "variants": []
    },
    {
        "name": "Black Pacific (sin arroz)",
        "category": "ROLLS PREMIUM",
        "price": 7490,
        "description": "Ligero, sabroso y sofisticado. Cobertura de palta con sésamo tostado, relleno sin arroz de atún fresco, camarón tempura crujiente, queso crema y ciboulette. Todo unido por una salsa acevichada que potencia los sabores y entrega frescura total.",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/1772879019257-1v7ahb.png",
        "variants": []
    },
    {
        "name": "Mango fuego",
        "category": "ROLLS PREMIUM",
        "price": 6900,
        "description": "Una combinación tropical y atrevida. Cobertura de mango fresco con sésamo tostado, relleno de salmón, palta y queso crema. Finalizado con una salsa de maracuyá al toque de merkén que mezcla dulzor, acidez y un picante sutil que sorprende desde el primer bocado.",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/1772878913132-n6k7igh.png",
        "variants": []
    },
    {
        "name": "Pink Nikkei",
        "category": "ROLLS PREMIUM",
        "price": 6900,
        "description": "Una propuesta innovadora y elegante. Cobertura de queso crema con sésamo negro, bañada en salsa y trozos de frutilla fresca. En su interior, salmón, palta y pepino que aportan equilibrio, frescura y textura en un roll dulce-salado simplemente irresistible.",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/1772878989392-cyw7vi.png",
        "variants": []
    },
    {
        "name": "Camarón-Queso",
        "category": "EMPANADAS",
        "price": 2500,
        "description": "*Frita, camarón y queso fundido",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Empanada Camarón Queso.jpg",
        "variants": []
    },
    {
        "name": "Carapacho Queso",
        "category": "EMPANADAS",
        "price": 2800,
        "description": "Queso mozzarella con bechamel",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Empanada Marisco.jpg",
        "variants": []
    },
    {
        "name": "Empanada de mariscos",
        "category": "EMPANADAS",
        "price": 2500,
        "description": "Variado de mariscos, sin camarón",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Empanada de mariscos.png",
        "variants": []
    },
    {
        "name": "Empanada Macha-Queso",
        "category": "EMPANADAS",
        "price": 2800,
        "description": null,
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Empanada Macha Queso.jpg",
        "variants": []
    },
    {
        "name": "Empanada Marisco",
        "category": "EMPANADAS",
        "price": 2500,
        "description": null,
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Empanada Marisco.jpg",
        "variants": []
    },
    {
        "name": "Empanada Queso",
        "category": "EMPANADAS",
        "price": 2000,
        "description": "*Frita, solo queso",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Empanada Queso.jpg",
        "variants": []
    },
    {
        "name": "Macha Queso",
        "category": "EMPANADAS",
        "price": 2800,
        "description": "*Frita, macha y queso mozzarella",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/_MG_6814.jpg",
        "variants": []
    },
    {
        "name": "Mix Empanadas (4 unidades)",
        "category": "EMPANADAS",
        "price": 8900,
        "description": null,
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Mix Empanadas.jpg",
        "variants": []
    },
    {
        "name": "Aros de cebolla",
        "category": "PAPAS / FRITOS",
        "price": 3500,
        "description": "*Porción individual crujiente",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Papas Fritas LoMASRico.png",
        "variants": []
    },
    {
        "name": "Camarones apanados",
        "category": "PAPAS / FRITOS",
        "price": 6500,
        "description": "*Extra grandes con salsa verde",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Apanados LoMASRico.png",
        "variants": []
    },
    {
        "name": "Papas a la crema",
        "category": "PAPAS / FRITOS",
        "price": 5900,
        "description": "Con mozzarella y cebollín (1-2 pers)",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Papas%20a%20la%20Crema.jpg",
        "variants": []
    },
    {
        "name": "Papas Fritas XL",
        "category": "PAPAS / FRITOS",
        "price": 4900,
        "description": null,
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Papas Fritas LoMASRico.png",
        "variants": []
    },
    {
        "name": "Papas LoMASRico",
        "category": "PAPAS / FRITOS",
        "price": 4500,
        "description": "*Papas sazonadas con aliño de la casa",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Papas%20Fritas%20LoMASRico.png",
        "variants": []
    },
    {
        "name": "Agua CACHANTUN 500cc",
        "category": "BEBIDAS",
        "price": 1400,
        "description": "Mineral gasificada",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Agua mineral Puyehue.png",
        "variants": []
    },
    {
        "name": "Agua Puyehue 500cc",
        "category": "BEBIDAS",
        "price": 1400,
        "description": "Mineral gasificada",
        "isActive": false,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Agua mineral Puyehue.png",
        "variants": []
    },
    {
        "name": "Coca Cola 1.5L",
        "category": "BEBIDAS",
        "price": 2500,
        "description": null,
        "isActive": false,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Coca Cola 591cc.jpg",
        "variants": []
    },
    {
        "name": "Coca Cola 591cc",
        "category": "BEBIDAS",
        "price": 1600,
        "description": "Normal",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Coca Cola 591cc.jpg",
        "variants": []
    },
    {
        "name": "Coca Cola Zero 1.5L",
        "category": "BEBIDAS",
        "price": 2500,
        "description": null,
        "isActive": false,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Coca Cola Zero 591cc.png",
        "variants": []
    },
    {
        "name": "Coca Cola Zero 591cc",
        "category": "BEBIDAS",
        "price": 1600,
        "description": "Sin azúcar",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Coca%20Cola%20591cc.jpg",
        "variants": []
    },
    {
        "name": "Jugo Natural",
        "category": "BEBIDAS",
        "price": 3200,
        "description": "*Fruta de la estación",
        "isActive": false,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Jugo Natural.jpg",
        "variants": []
    },
    {
        "name": "Kem Piña 1.5L",
        "category": "BEBIDAS",
        "price": 2200,
        "description": null,
        "isActive": false,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Kem Piña 350cc.jpeg",
        "variants": []
    },
    {
        "name": "Kem Piña 350cc",
        "category": "BEBIDAS",
        "price": 1400,
        "description": "Sabor piña",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Kem_Pina_350cc.jpeg",
        "variants": []
    },
    {
        "name": "Limon Soda 1.5L",
        "category": "BEBIDAS",
        "price": 2200,
        "description": null,
        "isActive": false,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Limon Soda 350cc.png",
        "variants": []
    },
    {
        "name": "Limon Soda 350cc",
        "category": "BEBIDAS",
        "price": 1400,
        "description": "Sabor limón",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Limon%20Soda%20350cc.png",
        "variants": []
    },
    {
        "name": "Limonada Albahaca",
        "category": "BEBIDAS",
        "price": 3500,
        "description": "*Sabor gourmet",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Limonada_Clasica.jpg",
        "variants": []
    },
    {
        "name": "Limonada Clásica",
        "category": "BEBIDAS",
        "price": 3000,
        "description": "*Elaborada con sumo de limón natural",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Limonada Clásica.jpg",
        "variants": []
    },
    {
        "name": "Limonada Menta",
        "category": "BEBIDAS",
        "price": 3500,
        "description": "*Menta y jengibre",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Limonada_Clasica.jpg",
        "variants": []
    },
    {
        "name": "Limonada Menta Jengibre",
        "category": "BEBIDAS",
        "price": 3500,
        "description": null,
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Limonada Clásica.jpg",
        "variants": []
    },
    {
        "name": "Monster 473cc",
        "category": "BEBIDAS",
        "price": 2500,
        "description": null,
        "isActive": false,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Monster 475cc.png",
        "variants": []
    },
    {
        "name": "Monster 475cc",
        "category": "BEBIDAS",
        "price": 2400,
        "description": "Energética (variedades)",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Monster%20475cc.png",
        "variants": []
    },
    {
        "name": "Ajo y Queso",
        "category": "PANCITOS",
        "price": 2500,
        "description": "Con queso mozzarella y salsa de la casa",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Pancitos con Ajo.jpg",
        "variants": []
    },
    {
        "name": "Al orégano (10 u)",
        "category": "PANCITOS",
        "price": 1500,
        "description": "Incluye salsa verde 100% natural",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Pancitos con Ajo.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Lo mas Rico",
        "category": "LO MÁS RICO",
        "price": 13900,
        "description": "Incluye base y 1 proteina a eleccion",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/Ceviche LoMASRico.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Peruano (350g)",
        "category": "CEVICHE PERUANO",
        "price": 10900,
        "description": "Receta tradicional peruana",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/peruano_lomasrico_1746715767G2anZ4.jpeg",
        "variants": []
    },
    {
        "name": "Ceviche Peruano (500g)",
        "category": "CEVICHE PERUANO",
        "price": 13400,
        "description": "Receta tradicional peruana",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/peruano_lomasrico_1746715767G2anZ4.jpeg",
        "variants": []
    },
    {
        "name": "Ceviche Peruano (750g)",
        "category": "CEVICHE PERUANO",
        "price": 18900,
        "description": "Receta tradicional peruana",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/peruano_lomasrico_1746715767G2anZ4.jpeg",
        "variants": []
    },
    {
        "name": "Ceviche Peruano (1KG)",
        "category": "CEVICHE PERUANO",
        "price": 22900,
        "description": "Receta tradicional peruana",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/peruano_lomasrico_1746715767G2anZ4.jpeg",
        "variants": []
    },
    {
        "name": "Ceviche Tropical (250g)",
        "category": "CEVICHE TROPICAL",
        "price": 5900,
        "description": "Con toques de mango y maracuyá",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/Ceviche Tropical.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Tropical (350g)",
        "category": "CEVICHE TROPICAL",
        "price": 8900,
        "description": "Con toques de mango y maracuyá",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/Ceviche Tropical.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Tropical (500g)",
        "category": "CEVICHE TROPICAL",
        "price": 11900,
        "description": "Con toques de mango y maracuyá",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/Ceviche Tropical.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Tropical (750g)",
        "category": "CEVICHE TROPICAL",
        "price": 16900,
        "description": "Con toques de mango y maracuyá",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/Ceviche Tropical.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Tropical (1KG)",
        "category": "CEVICHE TROPICAL",
        "price": 20900,
        "description": "Con toques de mango y maracuyá",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/Ceviche Tropical.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Veg",
        "category": "CEVICHE VEG",
        "price": 7900,
        "description": "*Champiñones marinados en leche de tigre",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Ceviche Veg.jpg",
        "variants": []
    },
    {
        "name": "Ceviche Vegano",
        "category": "CEVICHE VEG",
        "price": 12900,
        "description": "Base de champiñones y verduras",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "/assets/Ceviche Veg.jpg",
        "variants": []
    },
    {
        "name": "Crudo de Atún",
        "category": "CRUDOS",
        "price": 8900,
        "description": "*Cortes premium listos para disfrutar",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Crudo de Atún.jpeg",
        "variants": []
    },
    {
        "name": "Crudo de Salmón",
        "category": "CRUDOS",
        "price": 8900,
        "description": "*Cortes premium listos para disfrutar",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Crudo de Salmón.jpeg",
        "variants": []
    },
    {
        "name": "Leche de Tigre",
        "category": "PAPAS / FRITOS",
        "price": 4900,
        "description": "Concentrado de ceviche con trozos de pescado",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Leche de Tigre.jpg",
        "variants": []
    },
    {
        "name": "Pancitos horneados",
        "category": "PANCITOS",
        "price": 1900,
        "description": "Pancitos de ajo con salsa verde (10 unidades)",
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Pancitos con Ajo.jpg",
        "variants": []
    },
    {
        "name": "Papas a la Crema",
        "category": "PAPAS / FRITOS",
        "price": 4500,
        "description": null,
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Papas a la Crema.jpg",
        "variants": []
    },
    {
        "name": "Sopaipillas",
        "category": "EXTRAS",
        "price": 1990,
        "description": "3 o 10 unidades, masa 100% artesanal",
        "isActive": true,
        "isConfigurable": true,
        "maxProteins": 0,
        "imageUrl": "https://xnwbrdnorjafwwyfhysx.supabase.co/storage/v1/object/public/assets/Sopaipillas%2010%20uni.jpg",
        "variants": [
            {
                "name": "3 Unidades",
                "price": 1990,
                "isActive": true
            },
            {
                "name": "10 Unidades",
                "price": 5900,
                "isActive": true
            }
        ]
    },
    {
        "name": "Sopaipillas (10 unidades)",
        "category": "PAPAS / FRITOS",
        "price": 2500,
        "description": null,
        "isActive": true,
        "isConfigurable": false,
        "maxProteins": 0,
        "imageUrl": "/assets/Sopaipillas 10 uni.jpg",
        "variants": []
    }
];